// 프로젝트 공유 기억 — <project>/.loom/ 안의 파일들. CLI 도구의 경계를 넘어
// 에이전트들이 같은 맥락을 읽고 쌓는다. 본문은 프롬프트에 주입하지 않고(자동
// 주입 금지) 경로만 안내 — 에이전트가 필요할 때 Read 한다. 프로젝트 cwd 안이라
// 5개 CLI 모두 특별한 권한 플래그 없이 읽을 수 있다.
//   notes.md     — 사람·에이전트 양방향 공유 메모 (읽기 + durable 노트 추가)
//   analysis.md  — 최신 프로젝트 분석 뷰 (읽기 전용, /analyze 가 재생성)
//
// 정본(UI·히스토리)은 data/analysis/<id>.json — 이 .md 는 그것의 사람·에이전트용 뷰.

import path from "node:path";
import { z } from "zod";

export function notesPath(projectPath: string): string {
  return path.join(projectPath, ".loom", "notes.md");
}

export function analysisDocPath(projectPath: string): string {
  return path.join(projectPath, ".loom", "analysis.md");
}

// ── 분석 리포트 스키마 — 모델이 JSON 한 필드를 망가뜨려도 리포트 전체를 버리지
//    않도록 union·catch 로 흡수(읽기 시점 정규화). 분석 도메인 타입이라 여기 둔다.
const pct = z.coerce.number().transform((n) => Math.max(0, Math.min(100, Math.round(n))));
const riskItem = z.union([
  z.string().transform((text) => ({ text, severity: "medium" as const })),
  z.object({ text: z.string(), severity: z.enum(["high", "medium", "low"]).catch("medium") }),
]);
const suggestionItem = z.union([
  z.string().transform((text) => ({ text, effort: "medium" as const })),
  z.object({ text: z.string(), effort: z.enum(["small", "medium", "large"]).catch("medium") }),
]);
export const analysisReportSchema = z.object({
  summary: z.string(),
  stack: z.array(z.string()).default([]),
  languages: z.array(z.object({ name: z.string(), percent: pct })).default([]),
  health: z
    .object({ tests: pct, docs: pct, structure: pct, maintainability: pct })
    .partial()
    .default({}),
  metrics: z
    .object({ files: z.coerce.number().optional(), loc: z.coerce.number().optional() })
    .default({}),
  structure: z.array(z.object({ path: z.string(), desc: z.string() })).default([]),
  keyFiles: z.array(z.object({ path: z.string(), desc: z.string() })).default([]),
  risks: z.array(riskItem).default([]),
  suggestions: z.array(suggestionItem).default([]),
});
export type AnalysisReport = z.infer<typeof analysisReportSchema>;

export interface AnalysisRecord {
  analyzedAt: string;
  agent: string;
  runId: string;
  report: AnalysisReport;
}

/** 순수 — 분석 레코드를 에이전트·사람이 읽기 좋은 마크다운으로. <project>/.loom/
 *  analysis.md 에 쓰인다. 헤더에 출처(언제·누가)를 명시해 다른 에이전트가
 *  "이건 codex 가 본 구조"임을 알 수 있게 한다. */
export function renderAnalysisMarkdown(a: AnalysisRecord): string {
  const r = a.report;
  const l: string[] = [];
  l.push("<!-- Generated by loom on each /analyze. Latest project analysis — safe to read, will be overwritten. -->");
  l.push("# Project Analysis");
  l.push(`_Analyzed ${a.analyzedAt.slice(0, 16).replace("T", " ")} by @${a.agent}_`);
  l.push("");
  if (r.summary) l.push(r.summary, "");

  if (r.stack.length) l.push("## Stack", r.stack.map((s) => `- ${s}`).join("\n"), "");

  const h = r.health;
  if (Object.keys(h).length) {
    l.push("## Health (0–100)");
    const cells = (["tests", "docs", "structure", "maintainability"] as const).filter((k) => h[k] != null);
    l.push(`| ${cells.join(" | ")} |`);
    l.push(`| ${cells.map(() => "---").join(" | ")} |`);
    l.push(`| ${cells.map((k) => h[k]).join(" | ")} |`, "");
  }
  if (r.metrics.files != null || r.metrics.loc != null) {
    l.push(`Metrics: ${r.metrics.files ?? "?"} files · ${r.metrics.loc ?? "?"} LOC`, "");
  }

  if (r.structure.length) {
    l.push("## Structure");
    for (const s of r.structure) l.push(`- \`${s.path}\` — ${s.desc}`);
    l.push("");
  }
  if (r.keyFiles.length) {
    l.push("## Key files");
    for (const k of r.keyFiles) l.push(`- \`${k.path}\` — ${k.desc}`);
    l.push("");
  }
  if (r.risks.length) {
    l.push("## Risks");
    for (const x of r.risks) l.push(`- [${x.severity}] ${x.text}`);
    l.push("");
  }
  if (r.suggestions.length) {
    l.push("## Suggestions");
    for (const s of r.suggestions) l.push(`- [${s.effort}] ${s.text}`);
    l.push("");
  }
  return l.join("\n").trimEnd() + "\n";
}
